building AMS with adiak
llnl/AMS pull request #10
Opened 2023-09-28 16:03 UTC by r-yin

Added Adiak options to CMakeList to support Adiak calls inside main.cpp

2023-10-02 16:45 UTC, koparasy commented on CMakeLists.txt
> +
If only the example file calls the adiak API you don't need these lines here. You need to find_package at line 346.

2023-10-02 16:46 UTC, koparasy commented on examples/main.cpp
> +
Can you add all this init functions in a separate function and call it?

2023-10-02 16:46 UTC, koparasy commented on setup_env_with_pfa.sh
Please remove this file from the commit. We are not uploading setup recipes in the repository. Keep a copy of this on your local system.

2023-10-02 16:47 UTC, koparasy requested changes
Thank you for the commit and the additional functionality. This looks good to me besides the comments. Can you fix them? Thank you!

2024-03-06 16:53 UTC, slabasan commented
@koparasy This one can be closed, changes migrated to #56

2025-04-08 10:56 UTC, closed without merging